// Generates src/api/schema.d.ts from the committed OpenAPI document.
//
// Called through the library rather than the CLI: the CLI resolves its input as a URL,
// so a checkout under a folder with '#' in its name (such as "C#") loses everything
// after the '#'. Handing it the parsed document avoids path resolution entirely.
import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const input = new URL('../src/api/openapi.json', import.meta.url)
const output = new URL('../src/api/schema.d.ts', import.meta.url)

const document = JSON.parse(await readFile(input, 'utf8'))
const ast = await openapiTS(document)
const header = '// Generated by `npm run gen:api` from src/api/openapi.json. Do not edit.\n\n'
await writeFile(output, header + astToString(ast))
console.log('Wrote src/api/schema.d.ts')
